Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plumed.write_plumed('gmx/out/plumed_A1-U1.dat', targetRmp, 100, 100)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-10-4e13cd312cb2>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mplumed[0m[0;34m.[0m[0mwrite_plumed[0m[0;34m([0m[0;34m'gmx/out/plumed_A1-U1.dat'[0m[0;34m,[0m [0mtargetRmp[0m[0;34m,[0m [0;36m100[0m[0;34m,[0m [0;36m100[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/work/fretraj/fretraj/src/fretraj/restraints.py[0m in [0;36mwrite_plumed[0;34m(self, filename, R_mp, kappa_dist, Rmp_kappa)[0m
[1;32m     87[0m             [0mplumed_str[0m [0;34m+=[0m [0;34m'Rmp: DISTANCE ATOMS=mp1,mp2 NOPBC\n'[0m[0;34m[0m[0;34m[0m[0m
[1;32m     88[0m             [0mplumed_str[0m [0;34m+=[0m [0;34m'RESTRAINT ARG=Rmp AT={:0.1f} KAPPA={}\n'[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mR_mp[0m [0;34m/[0m [0;36m10[0m[0;34m,[0m [0mRmp_kappa[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 89[0;31m             [0;32mwith[0m [0mopen[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0;34m'w'[0m[0;34m)[0m [0;32mas[0m [0mf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     90[0m                 [0mf[0m[0;34m.[0m[0mwrite[0m[0;34m([0m[0mplumed_str[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     91[0m             [0;32mreturn[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'gmx/out/plumed_A1-U1.dat'
FileNotFoundError: [Errno 2] No such file or directory: 'gmx/out/plumed_A1-U1.dat'

